#!/usr/bin/env python3
"""
One-time builder: expand static_countries.json from 50 to 195 countries.
Uses World Bank API data (already fetched to /tmp/wb_countries.json) for
name, capital, region, and ISO codes. Supplements with compiled media,
language, currency, and cultural data for all UN member states + observers.

Run once:  python3 scripts/build_static_countries.py

⚠ THIS SCRIPT IS SPENT. It ran once in April 2026 and its output,
data/static_countries.json, has been hand-corrected many times since —
Gabon's government, Burundi's capital and other political facts have moved
on. Re-running it would silently overwrite those corrections with April's
snapshot. It is kept only as the record of how the file was first built.
To change a country, edit data/static_countries.json directly.
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STATIC = REPO / "data" / "static_countries.json"

def flag_emoji(iso2: str) -> str:
    return chr(0x1F1E6 + ord(iso2[0]) - ord("A")) + chr(0x1F1E6 + ord(iso2[1]) - ord("A"))

# World Bank region code → (region, default subregion)
WB_REGIONS = {
    "ECS": ("Europe", "Europe"),
    "LCN": ("Americas", "Latin America & Caribbean"),
    "MEA": ("Asia", "Middle East & North Africa"),
    "NAC": ("Americas", "Northern America"),
    "SAS": ("Asia", "Southern Asia"),
    "SSF": ("Africa", "Sub-Saharan Africa"),
    "EAS": ("Asia", "East Asia & Pacific"),
}

# ---------- COMPILED DATA FOR 145 NEW COUNTRIES ----------
# Each value: [subregion, currency, [languages], government, [industries],
#   overview, top_tv, top_radio, top_online_news, top_social]

D: dict[str, list] = {
# ---- AFRICA ----
"BEN": ["Western Africa", "West African CFA Franc (XOF)", ["French (official)", "Fon", "Yoruba"], "Presidential republic",
    ["Agriculture", "Cotton", "Services", "Construction"],
    "A West African republic with a growing services sector and significant cotton-based agricultural economy.",
    "ORTB, Canal 3, Golf TV", "ORTB Radio, Radio Planète", "La Nation, 24 Heures au Bénin",
    "Facebook, WhatsApp, YouTube, TikTok, Instagram"],
"BWA": ["Southern Africa", "Botswana Pula (BWP)", ["English (official)", "Setswana"], "Parliamentary republic",
    ["Diamond mining", "Tourism", "Cattle", "Financial services"],
    "One of Africa's most stable democracies, with a diamond-driven economy and growing tourism sector.",
    "BTV, e.tv Botswana", "Radio Botswana, Duma FM", "Mmegi Online, The Voice, Sunday Standard",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"BFA": ["Western Africa", "West African CFA Franc (XOF)", ["French (official)", "Mooré", "Dioula"], "Transitional government",
    ["Agriculture", "Gold mining", "Cotton", "Livestock"],
    "A landlocked West African country with a primarily agricultural economy and growing mining sector.",
    "RTB, BF1", "Radio Burkina, Savane FM", "LeFaso.net, Faso.net",
    "Facebook, WhatsApp, YouTube, TikTok"],
"BDI": ["Eastern Africa", "Burundian Franc (BIF)", ["Kirundi (official)", "French (official)", "English"], "Presidential republic",
    ["Agriculture", "Coffee", "Tea", "Light manufacturing"],
    "A small, densely populated East African country with an economy centered on subsistence agriculture.",
    "RTNB, Renaissance TV", "RTNB Radio, RPA, Isanganiro", "Iwacu, SOS Médias Burundi",
    "Facebook, WhatsApp, YouTube"],
"CPV": ["Western Africa", "Cape Verdean Escudo (CVE)", ["Portuguese (official)", "Kabuverdianu"], "Semi-presidential republic",
    ["Tourism", "Fishing", "Services", "Remittances"],
    "An Atlantic island nation off West Africa, known for its tourism sector and strong diaspora ties.",
    "TCV, Record TV Africa", "RCV, Praia FM", "A Semana, Inforpress",
    "Facebook, WhatsApp, YouTube, Instagram"],
"CAF": ["Middle Africa", "Central African CFA Franc (XAF)", ["French (official)", "Sango (official)"], "Presidential republic",
    ["Agriculture", "Timber", "Diamond mining", "Gold"],
    "A landlocked Central African country rich in natural resources but affected by prolonged instability.",
    "TVCA, Radio Ndeke Luka TV", "Radio Centrafrique, Radio Ndeke Luka", "Radio Ndeke Luka Online, Corbeau News",
    "Facebook, WhatsApp, YouTube"],
"TCD": ["Middle Africa", "Central African CFA Franc (XAF)", ["French (official)", "Arabic (official)"], "Transitional government",
    ["Oil", "Agriculture", "Livestock", "Cotton"],
    "A landlocked Saharan and Sahelian country whose economy relies heavily on oil exports.",
    "Télé Tchad, Electron TV", "RNT, Radio FM Liberté", "Alwihda Info, Tchadinfos",
    "Facebook, WhatsApp, YouTube"],
"COM": ["Eastern Africa", "Comorian Franc (KMF)", ["Comorian (official)", "Arabic (official)", "French (official)"], "Federal presidential republic",
    ["Agriculture", "Vanilla", "Cloves", "Fishing"],
    "A small Indian Ocean archipelago between Mozambique and Madagascar, with a largely agricultural economy.",
    "ORTC", "Radio Comores, Radio Ngazidja", "Al-Watwan, Comores Infos",
    "Facebook, WhatsApp"],
"COG": ["Middle Africa", "Central African CFA Franc (XAF)", ["French (official)", "Lingala", "Kituba"], "Presidential republic",
    ["Oil", "Timber", "Mining", "Agriculture"],
    "An oil-producing Central African country straddling the equator, with Brazzaville as its capital across the river from Kinshasa.",
    "Télé Congo, DRTV", "Radio Congo, Radio Brazzaville", "Les Dépêches de Brazzaville, Vox",
    "Facebook, WhatsApp, YouTube"],
"CIV": ["Western Africa", "West African CFA Franc (XOF)", ["French (official)", "Dioula", "Baoulé"], "Presidential republic",
    ["Cocoa", "Agriculture", "Oil refining", "Mining", "Telecommunications"],
    "The world's largest cocoa producer and one of West Africa's most dynamic economies.",
    "RTI, NCI, A+", "RTI Radio, Radio Côte d'Ivoire, Nostalgie", "Fratmat, Abidjan.net, Connectionivoirienne",
    "Facebook, WhatsApp, YouTube, TikTok, Instagram"],
"DJI": ["Eastern Africa", "Djiboutian Franc (DJF)", ["French (official)", "Arabic (official)", "Somali", "Afar"], "Presidential republic",
    ["Services", "Port logistics", "Military bases", "Telecommunications"],
    "A strategically located Horn of Africa nation hosting major international military bases and serving as a regional shipping hub.",
    "RTD", "Radio Djibouti", "La Nation Djibouti, ADI",
    "Facebook, WhatsApp, YouTube, TikTok"],
"GNQ": ["Middle Africa", "Central African CFA Franc (XAF)", ["Spanish (official)", "French (official)", "Portuguese (official)"], "Presidential republic",
    ["Oil", "Gas", "Timber", "Fishing"],
    "A small, oil-rich Central African country and one of the continent's highest per-capita income nations.",
    "TVGE", "Radio Nacional, Radio Asonga", "Guinea Ecuatorial Press",
    "Facebook, WhatsApp, YouTube"],
"ERI": ["Eastern Africa", "Eritrean Nakfa (ERN)", ["Tigrinya", "Arabic", "English"], "Presidential republic",
    ["Agriculture", "Mining", "Fishing", "Light manufacturing"],
    "A Horn of Africa country on the Red Sea coast with a highly controlled media environment.",
    "Eri-TV", "Radio Dimtsi Hafash, Radio Zara", "Shabait.com, Eritrea Profile",
    "Facebook, WhatsApp, YouTube"],
"SWZ": ["Southern Africa", "Swazi Lilangeni (SZL)", ["English (official)", "Swazi (official)"], "Absolute monarchy",
    ["Sugar", "Soft drinks", "Textiles", "Agriculture"],
    "Africa's last absolute monarchy, a small landlocked kingdom known for its sugar and textile industries.",
    "Eswatini TV", "Swazi Observer Radio, VOC Radio", "Swazi Observer, Times of Eswatini",
    "Facebook, WhatsApp, YouTube, Instagram"],
"GAB": ["Middle Africa", "Central African CFA Franc (XAF)", ["French (official)"], "Transitional government",
    ["Oil", "Manganese", "Timber", "Agriculture"],
    "An oil-rich equatorial nation with one of Sub-Saharan Africa's highest per-capita incomes.",
    "Gabon 1ère, TV+", "Radio Gabon, Africa No. 1", "L'Union, Gabon Review",
    "Facebook, WhatsApp, YouTube, Instagram"],
"GMB": ["Western Africa", "Gambian Dalasi (GMD)", ["English (official)", "Mandinka", "Wolof", "Fula"], "Presidential republic",
    ["Agriculture", "Tourism", "Fishing", "Remittances"],
    "A narrow West African country along the Gambia River, surrounded by Senegal on three sides.",
    "GRTS", "GRTS Radio, Paradise FM, Unique FM", "The Point, Foroyaa, The Standard",
    "Facebook, WhatsApp, YouTube, TikTok"],
"GIN": ["Western Africa", "Guinean Franc (GNF)", ["French (official)", "Fula", "Mandinka", "Susu"], "Transitional government",
    ["Bauxite mining", "Agriculture", "Gold mining", "Fishing"],
    "Home to the world's largest bauxite reserves, a West African country with significant mineral wealth.",
    "RTG, Évasion TV", "RTG Radio, Espace FM, FIM FM", "Guinéenews, Mosaiqueguinee",
    "Facebook, WhatsApp, YouTube"],
"GNB": ["Western Africa", "West African CFA Franc (XOF)", ["Portuguese (official)", "Crioulo"], "Semi-presidential republic",
    ["Agriculture", "Cashew nuts", "Fishing", "Timber"],
    "A small West African country and one of the world's largest cashew nut producers.",
    "TGB", "Rádio Nacional, Rádio Pindjiguiti", "Lusa Guinea-Bissau, Bantaba di Guiné",
    "Facebook, WhatsApp"],
"LSO": ["Southern Africa", "Lesotho Loti (LSL)", ["Sesotho (official)", "English (official)"], "Constitutional monarchy",
    ["Textiles", "Agriculture", "Water exports", "Diamond mining"],
    "A mountainous kingdom entirely surrounded by South Africa, known as the 'Kingdom in the Sky.'",
    "Lesotho TV", "Radio Lesotho, MoAfrika FM, People's Choice FM", "Lesotho Times, Informative",
    "Facebook, WhatsApp, YouTube"],
"LBR": ["Western Africa", "Liberian Dollar (LRD)", ["English (official)"], "Presidential republic",
    ["Iron ore", "Rubber", "Agriculture", "Shipping registry"],
    "Africa's oldest republic, founded by freed American slaves, now rebuilding after civil conflict.",
    "LNTV, Clar TV", "ELBC, Radio Veritas, OK FM", "FrontPageAfrica, Daily Observer, Bush Chicken",
    "Facebook, WhatsApp, YouTube"],
"LBY": ["Northern Africa", "Libyan Dinar (LYD)", ["Arabic (official)"], "Divided government",
    ["Oil", "Gas", "Agriculture", "Construction"],
    "A North African country with Africa's largest proven oil reserves, navigating post-conflict political division.",
    "Libya Al-Ahrar, 218 TV, Al-Tanasuh", "Libya FM, Radio Alhurra", "Libya Herald, 218TV.net, Libyan Express",
    "Facebook, WhatsApp, YouTube, TikTok, Instagram"],
"MWI": ["Eastern Africa", "Malawian Kwacha (MWK)", ["English (official)", "Chichewa (official)"], "Presidential republic",
    ["Agriculture", "Tobacco", "Tea", "Sugar"],
    "A landlocked southeastern African country known as the 'Warm Heart of Africa,' with an economy based on agriculture.",
    "MBC TV, Times TV", "MBC Radio, Zodiak Broadcasting, Capital FM", "Malawi Nation, Nyasa Times, Malawi24",
    "Facebook, WhatsApp, YouTube"],
"MLI": ["Western Africa", "West African CFA Franc (XOF)", ["French (official)", "Bambara"], "Transitional government",
    ["Agriculture", "Gold mining", "Cotton", "Livestock"],
    "A large landlocked West African country with a rich cultural heritage and a predominantly agricultural economy.",
    "ORTM, Africable, Joliba TV", "ORTM Radio, Radio Kayira, Radio Liberté", "Maliweb, Journal du Mali, Bamada.net",
    "Facebook, WhatsApp, YouTube, TikTok"],
"MRT": ["Western Africa", "Mauritanian Ouguiya (MRU)", ["Arabic (official)", "French"], "Presidential republic",
    ["Iron ore", "Fishing", "Oil", "Livestock"],
    "A large, sparsely populated Saharan country bridging Arab North Africa and Sub-Saharan West Africa.",
    "Télévision de Mauritanie, Al Mourabitoune", "Radio Mauritanie, Radio Kobeni", "AMI, Sahara Media, Le Calame",
    "Facebook, WhatsApp, YouTube"],
"MUS": ["Eastern Africa", "Mauritian Rupee (MUR)", ["English (official)", "French", "Creole", "Hindi"], "Parliamentary republic",
    ["Tourism", "Financial services", "Textiles", "Sugar", "ICT"],
    "A prosperous Indian Ocean island nation known for tourism, financial services, and its multicultural society.",
    "MBC, Top TV", "MBC Radio, Radio Plus, Radio One", "L'Express, Le Défi Media, ION News",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"NAM": ["Southern Africa", "Namibian Dollar (NAD)", ["English (official)", "Afrikaans", "German", "Oshiwambo"], "Presidential republic",
    ["Mining", "Tourism", "Agriculture", "Fishing"],
    "A sparsely populated southwestern African country known for the Namib Desert, wildlife tourism, and diamond mining.",
    "NBC, One Africa TV", "NBC Radio, Radio Energy, Radiowave", "The Namibian, New Era, Namibian Sun",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"NER": ["Western Africa", "West African CFA Franc (XOF)", ["French (official)", "Hausa", "Zarma"], "Transitional government",
    ["Agriculture", "Uranium mining", "Livestock", "Oil"],
    "A landlocked Sahelian country and one of the world's largest uranium producers.",
    "Télé Sahel, Bonferey TV, Labari TV", "Voix du Sahel, Radio Anfani, Tambara", "ActuNiger, Le Sahel, Nigerdiaspora",
    "Facebook, WhatsApp, YouTube"],
"RWA": ["Eastern Africa", "Rwandan Franc (RWF)", ["Kinyarwanda (official)", "English (official)", "French (official)"], "Presidential republic",
    ["Agriculture", "Tourism", "Mining", "ICT"],
    "A small, densely populated East African nation that has become a model for technology-driven development in Africa.",
    "RBA, TV1 Rwanda, TV10", "Radio Rwanda, KT Radio, Flash FM", "The New Times, Kigali Today, Igihe",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"STP": ["Middle Africa", "São Tomé and Príncipe Dobra (STN)", ["Portuguese (official)"], "Semi-presidential republic",
    ["Cocoa", "Tourism", "Fishing", "Agriculture"],
    "One of Africa's smallest countries, a two-island nation in the Gulf of Guinea.",
    "TVS", "Radio Nacional, Radio Jubilar", "Téla Nón, STP-Press",
    "Facebook, WhatsApp"],
"SEN": ["Western Africa", "West African CFA Franc (XOF)", ["French (official)", "Wolof", "Fula", "Serer"], "Presidential republic",
    ["Agriculture", "Fishing", "Mining", "Tourism", "Services"],
    "A West African democracy known for its stability, vibrant culture, and growing tech scene in Dakar.",
    "RTS, TFM, 2STV, Sen TV", "RFM, Sud FM, iRadio, Walf FM", "Seneweb, Dakaractu, Le Soleil, Emedia",
    "Facebook, WhatsApp, YouTube, TikTok, Instagram"],
"SYC": ["Eastern Africa", "Seychellois Rupee (SCR)", ["Seychellois Creole (official)", "English (official)", "French (official)"], "Presidential republic",
    ["Tourism", "Fishing", "Financial services"],
    "A small Indian Ocean archipelago east of Africa, known for its tourism and one of Africa's highest per-capita incomes.",
    "SBC", "SBC Radio, Pure FM", "Seychelles Nation, Today in Seychelles",
    "Facebook, WhatsApp, YouTube, Instagram"],
"SLE": ["Western Africa", "Sierra Leonean Leone (SLE)", ["English (official)", "Krio", "Mende", "Temne"], "Presidential republic",
    ["Mining", "Agriculture", "Fishing", "Manufacturing"],
    "A West African country on the Atlantic coast, rebuilding its economy after civil conflict and the Ebola crisis.",
    "SLBC", "SLBC Radio, Citizen Radio, Radio Democracy", "Awoko, Sierra Leone Telegraph, Politico SL",
    "Facebook, WhatsApp, YouTube"],
"SOM": ["Eastern Africa", "Somali Shilling (SOS)", ["Somali (official)", "Arabic (official)"], "Federal parliamentary republic",
    ["Livestock", "Telecommunications", "Remittances", "Agriculture"],
    "A Horn of Africa country with a pastoral economy and one of the continent's most dynamic mobile money and telecom sectors despite ongoing conflict.",
    "SNTV, Universal TV, Horn Cable", "Radio Mogadishu, Radio Dalsan, Radio Kulmiye", "Garowe Online, Hiiraan Online, Caasimada",
    "Facebook, WhatsApp, YouTube, TikTok"],
"SSD": ["Eastern Africa", "South Sudanese Pound (SSP)", ["English (official)", "Arabic"], "Presidential republic",
    ["Oil", "Agriculture", "Forestry", "Livestock"],
    "The world's newest country (independent 2011), rich in oil but affected by civil conflict.",
    "SSBC, Eye Radio TV", "Radio Miraya, Eye Radio, Capital FM", "Eye Radio Online, Radio Tamazuj, Sudan Tribune",
    "Facebook, WhatsApp, YouTube"],
"TZA": ["Eastern Africa", "Tanzanian Shilling (TZS)", ["Swahili (official)", "English (official)"], "Presidential republic",
    ["Agriculture", "Mining", "Tourism", "Manufacturing"],
    "An East African country with significant natural resources, growing tourism, and a major trade corridor through Dar es Salaam.",
    "TBC, ITV, Azam TV, Star TV", "TBC Radio, Radio Free Africa, Clouds FM", "The Citizen, Daily News, Mwananchi, IPP Media",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"TGO": ["Western Africa", "West African CFA Franc (XOF)", ["French (official)", "Ewe", "Kabiyé"], "Presidential republic",
    ["Agriculture", "Phosphate mining", "Port services", "Commerce"],
    "A narrow West African country with a major deepwater port in Lomé that serves as a regional trade hub.",
    "TVT, LCF", "Radio Lomé, Nana FM, Radio Victoire", "RepublicOfTogo.com, Togofirst, Icilome",
    "Facebook, WhatsApp, YouTube, TikTok"],
"TUN": ["Northern Africa", "Tunisian Dinar (TND)", ["Arabic (official)", "French (widely spoken)"], "Presidential republic",
    ["Manufacturing", "Tourism", "Agriculture", "Oil and gas", "ICT"],
    "A North African country at the crossroads of the Mediterranean, known as the birthplace of the Arab Spring and for its educated workforce.",
    "Watania 1, Nessma TV, Hannibal TV, Al Hiwar", "Radio Tunis, Mosaïque FM, Shems FM, Express FM", "Business News, Webmanagercenter, Nawaat, Leaders",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"ZMB": ["Eastern Africa", "Zambian Kwacha (ZMW)", ["English (official)", "Bemba", "Nyanja", "Tonga"], "Presidential republic",
    ["Copper mining", "Agriculture", "Tourism", "Energy"],
    "A landlocked southern African country and one of the world's top copper producers.",
    "ZNBC, Diamond TV, Prime TV", "ZNBC Radio, Hot FM, QFM", "Lusaka Times, Zambia Daily Mail, Mwebantu",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"ZWE": ["Eastern Africa", "Zimbabwe Gold (ZiG)", ["English", "Shona", "Ndebele"], "Presidential republic",
    ["Mining", "Agriculture", "Tourism", "Manufacturing"],
    "A landlocked southern African country rich in minerals and with a strong agricultural heritage, navigating economic reforms.",
    "ZBC TV, 3K TV", "ZBC Radio, Star FM, ZiFM Stereo", "NewsDay, The Herald, ZimLive, New Zimbabwe",
    "Facebook, WhatsApp, YouTube, Instagram"],

# ---- AMERICAS ----
"ATG": ["Caribbean", "East Caribbean Dollar (XCD)", ["English (official)"], "Constitutional monarchy",
    ["Tourism", "Construction", "Financial services"],
    "A twin-island Caribbean nation whose economy is driven by tourism and offshore financial services.",
    "ABS TV", "ABS Radio, Observer Radio", "Antigua Observer, ANR",
    "Facebook, WhatsApp, YouTube, Instagram"],
"BHS": ["Caribbean", "Bahamian Dollar (BSD)", ["English (official)"], "Constitutional monarchy",
    ["Tourism", "Financial services", "Shipping"],
    "An Atlantic archipelago and major Caribbean tourism destination with a significant offshore banking sector.",
    "ZNS TV, Our News", "ZNS Radio, Love 97, Guardian Radio", "Tribune242, Eyewitness News, Nassau Guardian",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"BRB": ["Caribbean", "Barbadian Dollar (BBD)", ["English (official)"], "Parliamentary republic",
    ["Tourism", "Financial services", "Manufacturing", "Sugar"],
    "The easternmost Caribbean island, a recently proclaimed republic with a strong tourism and financial services sector.",
    "CBC TV", "VOB, Starcom Network (SLAM, Hott, Gospel)", "Barbados Today, Nation News, Loop Barbados",
    "Facebook, WhatsApp, YouTube, Instagram"],
"BLZ": ["Central America", "Belize Dollar (BZD)", ["English (official)", "Spanish", "Kriol"], "Constitutional monarchy",
    ["Tourism", "Agriculture", "Oil", "Fishing"],
    "The only English-speaking country in Central America, known for its barrier reef and ecotourism.",
    "Channel 5, Channel 7, Plus TV", "Love FM, KREM FM, Estereo Amor", "Breaking Belize News, Amandala, Channel 5 News",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"BOL": ["South America", "Boliviano (BOB)", ["Spanish (official)", "Quechua", "Aymara", "Guaraní"], "Presidential republic",
    ["Mining", "Natural gas", "Agriculture", "Manufacturing"],
    "A landlocked South American country with significant natural gas reserves and diverse indigenous cultures.",
    "Bolivision, ATB, Unitel, Red Uno", "Radio Fides, Panamericana, Erbol", "El Deber, Página Siete, Los Tiempos, La Razón",
    "WhatsApp, Facebook, YouTube, TikTok, Instagram"],
"CHL": ["South America", "Chilean Peso (CLP)", ["Spanish (official)"], "Presidential republic",
    ["Copper mining", "Agriculture", "Fishing", "Services", "Lithium"],
    "South America's most economically stable country and the world's largest copper producer, with a strong media market.",
    "TVN, Canal 13, Mega, CHV, La Red", "Bío-Bío, Cooperativa, ADN Radio, Agricultura", "Emol, BioBioChile, La Tercera, El Mostrador, CIPER",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"CRI": ["Central America", "Costa Rican Colón (CRC)", ["Spanish (official)"], "Presidential republic",
    ["Technology", "Tourism", "Agriculture", "Medical devices"],
    "Known for its stable democracy, environmental policies, and growing tech sector, Costa Rica is a Central American hub for foreign investment.",
    "Teletica, Repretel, Trece", "Columbia, Monumental, Radio Nacional", "La Nación, CRHoy, Delfino, Ameliarueda",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"CUB": ["Caribbean", "Cuban Peso (CUP)", ["Spanish (official)"], "One-party socialist republic",
    ["Tourism", "Tobacco", "Nickel mining", "Sugar", "Biotechnology"],
    "A Caribbean socialist state with a state-controlled media environment and a strong tradition in health, education, and biotechnology.",
    "Cubavisión, Tele Rebelde, Canal Educativo", "Radio Rebelde, Radio Reloj, Radio Progreso", "Granma, CubaDebate, 14ymedio, Juventud Rebelde",
    "Facebook, WhatsApp, YouTube"],
"DMA": ["Caribbean", "East Caribbean Dollar (XCD)", ["English (official)", "French Creole"], "Parliamentary republic",
    ["Agriculture", "Tourism", "Ecotourism", "Fishing"],
    "A volcanic Caribbean island known as the 'Nature Isle of the Caribbean,' with a small but growing ecotourism sector.",
    "DBS TV, Marpin TV", "DBS Radio, Kairi FM, Q95", "Dominica News Online, The Sun",
    "Facebook, WhatsApp, YouTube"],
"DOM": ["Caribbean", "Dominican Peso (DOP)", ["Spanish (official)"], "Presidential republic",
    ["Tourism", "Mining", "Manufacturing", "Agriculture", "Remittances"],
    "The largest Caribbean economy, sharing the island of Hispaniola with Haiti and home to the region's busiest tourism sector.",
    "Telesistema, Teleantillas, Color Visión, CDN", "La Z101, CDN Radio, Zol FM", "Diario Libre, Listín Diario, Noticias SIN, Acento",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"ECU": ["South America", "United States Dollar (USD)", ["Spanish (official)", "Quechua", "Shuar"], "Presidential republic",
    ["Oil", "Agriculture", "Fishing", "Mining", "Tourism"],
    "An equatorial South American country spanning the Andes and Amazon, with a dollarized economy reliant on oil and agriculture.",
    "Ecuavisa, TC Televisión, Teleamazonas, RTS", "Radio Quito, Ecuadoradio, Sonorama", "El Comercio, El Universo, Primicias, GK",
    "WhatsApp, Facebook, YouTube, TikTok, Instagram"],
"SLV": ["Central America", "United States Dollar (USD)", ["Spanish (official)"], "Presidential republic",
    ["Manufacturing", "Textiles", "Agriculture", "Remittances"],
    "The smallest and most densely populated country in Central America, known for its Bitcoin legal tender experiment.",
    "TCS, Canal 12, Canal 33", "YSU Radio Nacional, Radio 102 Nueve, La Mejor FM", "El Diario de Hoy, La Prensa Gráfica, El Faro, Revista Factum",
    "WhatsApp, Facebook, YouTube, TikTok, Instagram"],
"GRD": ["Caribbean", "East Caribbean Dollar (XCD)", ["English (official)"], "Constitutional monarchy",
    ["Tourism", "Nutmeg", "Agriculture", "Financial services"],
    "Known as the 'Spice Isle,' a small Caribbean nation and one of the world's largest nutmeg producers.",
    "GBN TV", "GBN Radio, Real FM, City Sound", "Now Grenada, The New Today",
    "Facebook, WhatsApp, YouTube"],
"GTM": ["Central America", "Guatemalan Quetzal (GTQ)", ["Spanish (official)", "K'iche'", "Kaqchikel", "21 Maya languages"], "Presidential republic",
    ["Agriculture", "Manufacturing", "Textiles", "Remittances", "Tourism"],
    "Central America's most populous country with a large indigenous Maya population and an economy powered by agriculture and remittances.",
    "Nuestro Diario TV, Guatevisión, Canal Antigua, Telediario", "Emisoras Unidas, Radio Punto, Sonora", "Prensa Libre, Soy502, Plaza Pública, Nómada",
    "WhatsApp, Facebook, YouTube, TikTok, Instagram"],
"GUY": ["South America", "Guyanese Dollar (GYD)", ["English (official)", "Hindi", "Urdu", "Creolese"], "Presidential republic",
    ["Oil and gas", "Gold mining", "Bauxite", "Sugar", "Rice"],
    "South America's only English-speaking country, experiencing rapid growth driven by newly discovered offshore oil reserves.",
    "NCN, DTV8", "NCN Radio, Hits & Jams, Radio Guyana", "Stabroek News, Kaieteur News, Demerara Waves",
    "Facebook, WhatsApp, YouTube, Instagram"],
"HTI": ["Caribbean", "Haitian Gourde (HTG)", ["French (official)", "Haitian Creole (official)"], "Semi-presidential republic",
    ["Agriculture", "Textiles", "Remittances", "Construction"],
    "The Caribbean's most populous French-speaking country, facing significant humanitarian and governance challenges.",
    "Télé Haiti, TNH, Radio Télévision Caraïbes", "Radio Métropole, Radio Caraïbes, Radio Kiskeya", "Le Nouvelliste, AyiboPost, Juno7",
    "Facebook, WhatsApp, YouTube"],
"HND": ["Central America", "Honduran Lempira (HNL)", ["Spanish (official)"], "Presidential republic",
    ["Agriculture", "Manufacturing", "Textiles", "Remittances"],
    "A Central American country with a significant agricultural sector and growing manufacturing base.",
    "Televicentro, TSi, HCH", "HRN, Radio América, La Ceiba", "La Prensa, El Heraldo, Proceso Digital, Criterio",
    "WhatsApp, Facebook, YouTube, TikTok, Instagram"],
"JAM": ["Caribbean", "Jamaican Dollar (JMD)", ["English (official)", "Jamaican Patois"], "Constitutional monarchy",
    ["Tourism", "Mining", "Agriculture", "Services", "Remittances"],
    "A Caribbean island nation with outsized global cultural influence through reggae, dancehall, and athletics.",
    "TVJ, CVM TV, Hype TV", "RJR, IRIE FM, ZIP FM, Nationwide Radio", "The Gleaner, Jamaica Observer, Loop Jamaica",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"KNA": ["Caribbean", "East Caribbean Dollar (XCD)", ["English (official)"], "Constitutional monarchy",
    ["Tourism", "Financial services", "Manufacturing"],
    "A two-island Caribbean nation and the smallest sovereign state in the Americas.",
    "ZIZ TV", "ZIZ Radio, WINN FM", "SKNVibes, The Observer",
    "Facebook, WhatsApp, YouTube"],
"LCA": ["Caribbean", "East Caribbean Dollar (XCD)", ["English (official)", "Saint Lucian Creole"], "Constitutional monarchy",
    ["Tourism", "Agriculture", "Financial services", "Manufacturing"],
    "A Caribbean island known for its volcanic peaks, the Pitons, and its strong tourism-based economy.",
    "HTS, DBS TV", "Radio St. Lucia, Hot FM, RCI", "St. Lucia Times, Loop News, St. Lucia News Online",
    "Facebook, WhatsApp, YouTube, Instagram"],
"VCT": ["Caribbean", "East Caribbean Dollar (XCD)", ["English (official)"], "Constitutional monarchy",
    ["Agriculture", "Tourism", "Construction", "Fishing"],
    "A Caribbean multi-island country in the Grenadines chain, with a growing tourism sector.",
    "SVG TV", "NBC Radio, Hot 97, Hitz FM", "iWitness News, Searchlight, News784",
    "Facebook, WhatsApp, YouTube"],
"NIC": ["Central America", "Nicaraguan Córdoba (NIO)", ["Spanish (official)"], "Presidential republic",
    ["Agriculture", "Mining", "Manufacturing", "Textiles"],
    "The largest country in Central America by area, with an economy based on agriculture and a constrained press environment.",
    "Canal 2, Canal 8, Canal 10, Canal 4", "Radio Nicaragua, Radio Corporación, Radio La Primerísima", "Confidencial, 100% Noticias (exile), La Prensa",
    "WhatsApp, Facebook, YouTube, TikTok"],
"PAN": ["Central America", "Panamanian Balboa / US Dollar (PAB/USD)", ["Spanish (official)"], "Presidential republic",
    ["Services", "Panama Canal operations", "Finance", "Tourism", "Logistics"],
    "A Central American country whose economy revolves around the Panama Canal, making it a global trade and finance hub.",
    "TVN, Telemetro, RPC TV, Nex TV", "RPC Radio, Radio Panamá, KW Continente", "La Prensa, TVN Noticias, Telemetro Reporta",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"PRY": ["South America", "Paraguayan Guaraní (PYG)", ["Spanish (official)", "Guaraní (official)"], "Presidential republic",
    ["Agriculture", "Soybean", "Hydroelectric power", "Cattle ranching"],
    "A landlocked South American country with major hydroelectric capacity and a large agricultural sector.",
    "SNT, Telefuturo, Canal 13, RPC", "Radio Ñandutí, ABC Cardinal, Monumental", "ABC Color, Última Hora, La Nación, E'a",
    "WhatsApp, Facebook, YouTube, TikTok, Instagram"],
"SUR": ["South America", "Surinamese Dollar (SRD)", ["Dutch (official)", "Sranan Tongo", "Hindi", "Javanese"], "Presidential republic",
    ["Mining", "Oil", "Agriculture", "Forestry"],
    "South America's smallest country by population, a former Dutch colony with a richly diverse multiethnic society.",
    "STVS, Apintie TV, ATV", "SRS, Radio Apintie, Radio 10", "De Ware Tijd, Dagblad Suriname, Starnieuws",
    "Facebook, WhatsApp, YouTube"],
"TTO": ["Caribbean", "Trinidad and Tobago Dollar (TTD)", ["English (official)"], "Parliamentary republic",
    ["Oil and gas", "Petrochemicals", "Manufacturing", "Tourism"],
    "The Caribbean's largest oil and gas producer, a twin-island republic with a diverse and vibrant media scene.",
    "CNC3, TV6, TTT, CCN", "i95.5, Wack Radio, Red 96.7, Talk City", "Trinidad Express, Newsday, Loop TT, Guardian Media",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"URY": ["South America", "Uruguayan Peso (UYU)", ["Spanish (official)"], "Presidential republic",
    ["Agriculture", "Cattle ranching", "Software", "Tourism", "Renewable energy"],
    "One of South America's most stable and progressive democracies, with strong institutions and a highly connected population.",
    "Canal 4, Canal 10, Canal 12, Teledoce", "Sarandí, El Espectador, Carve, Océano FM", "El País, El Observador, Montevideo Portal, la diaria",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],

# ---- ASIA & MIDDLE EAST ----
"ARM": ["Western Asia", "Armenian Dram (AMD)", ["Armenian (official)"], "Parliamentary republic",
    ["Mining", "Agriculture", "IT", "Tourism"],
    "A small South Caucasus country with a growing IT sector and a large global diaspora.",
    "Armenia TV, Shant TV, Armenia 1", "Public Radio of Armenia, Radio Van", "News.am, CivilNet, Hetq",
    "Facebook, WhatsApp, YouTube, Instagram, Telegram"],
"AZE": ["Western Asia", "Azerbaijani Manat (AZN)", ["Azerbaijani (official)"], "Presidential republic",
    ["Oil and gas", "Agriculture", "Tourism", "Telecommunications"],
    "An oil-rich South Caucasus country on the Caspian Sea with significant energy exports.",
    "AzTV, ANS TV, Space TV, İTV", "Azerbaijan Radio, ASAN Radio, ANS", "Trend.az, Haqqin.az, Meydan TV",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"BHR": ["Western Asia", "Bahraini Dinar (BHD)", ["Arabic (official)", "English (widely spoken)"], "Constitutional monarchy",
    ["Oil and gas", "Financial services", "Aluminum", "Tourism"],
    "A small but wealthy Gulf island kingdom with a diversified economy and a major financial services sector.",
    "BTV, Al Rai TV", "Radio Bahrain, Al Jazeera FM", "Gulf Daily News, Al Ayam, Al Wasat",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Snapchat"],
"BTN": ["Southern Asia", "Bhutanese Ngultrum (BTN)", ["Dzongkha (official)"], "Constitutional monarchy",
    ["Hydroelectric power", "Tourism", "Agriculture", "Forestry"],
    "A Himalayan kingdom known for its Gross National Happiness philosophy and carefully managed tourism sector.",
    "BBS (Bhutan Broadcasting Service)", "BBS Radio, Kuzoo FM", "Kuensel, BBS News, The Bhutanese",
    "Facebook, WhatsApp, YouTube, WeChat"],
"BRN": ["South-Eastern Asia", "Brunei Dollar (BND)", ["Malay (official)", "English"], "Absolute monarchy",
    ["Oil and gas", "Financial services", "Halal industry"],
    "A small, wealthy sultanate on the island of Borneo, one of the richest countries in Asia per capita.",
    "RTB", "RTB Radio, Pelangi FM, Kristal FM", "Borneo Bulletin, BruDirect",
    "WhatsApp, Facebook, YouTube, Instagram"],
"KHM": ["South-Eastern Asia", "Cambodian Riel (KHR)", ["Khmer (official)"], "Parliamentary monarchy",
    ["Garment manufacturing", "Tourism", "Agriculture", "Construction"],
    "A Southeast Asian country with ancient Angkor heritage, a young population, and a fast-growing garment industry.",
    "TVK, CTN, Bayon TV, TV5 Cambodia", "National Radio of Cambodia, RFI Khmer, Apsara Radio", "Phnom Penh Post, Khmer Times, VOD, CamboJA News",
    "Facebook, WhatsApp, YouTube, TikTok, Telegram"],
"GEO": ["Western Asia", "Georgian Lari (GEL)", ["Georgian (official)"], "Parliamentary republic",
    ["Agriculture", "Tourism", "Mining", "Wine production"],
    "A South Caucasus country at the crossroads of Europe and Asia, known for its ancient winemaking tradition and growing tech sector.",
    "GPB, Imedi TV, Rustavi 2, TV Pirveli", "Georgian Public Broadcasting Radio, Radio Imedi", "Civil.ge, Agenda.ge, On.ge, Tabula",
    "Facebook, WhatsApp, YouTube, Instagram, Telegram"],
"ISR": ["Western Asia", "Israeli New Shekel (ILS)", ["Hebrew (official)", "Arabic"], "Parliamentary republic",
    ["Technology", "Diamond cutting", "Agriculture", "Defense", "Pharmaceuticals"],
    "A technologically advanced Middle Eastern country and a global hub for startups and innovation.",
    "Channel 12, Channel 13, KAN, i24NEWS", "Galatz, Kan Radio, Reshet Bet, 103FM", "Ynet, Haaretz, Times of Israel, Walla, i24NEWS",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"JOR": ["Western Asia", "Jordanian Dinar (JOD)", ["Arabic (official)"], "Constitutional monarchy",
    ["Services", "Tourism", "Pharmaceuticals", "Mining", "ICT"],
    "A stable Middle Eastern kingdom hosting significant refugee populations and serving as a regional diplomatic hub.",
    "JRTV, Roya TV, Al Mamlaka TV", "Radio Jordan, Mazaj FM, Sawt Al Ghad", "Jordan Times, Ammon News, Roya News, Hala Akhbar",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"KAZ": ["Central Asia", "Kazakhstani Tenge (KZT)", ["Kazakh (official)", "Russian (official)"], "Presidential republic",
    ["Oil and gas", "Mining", "Agriculture", "Manufacturing"],
    "Central Asia's largest economy and the world's largest landlocked country, rich in oil and mineral resources.",
    "Khabar, KTK, Channel One Eurasia, Astana TV", "Kazakh Radio, Tengri FM, NS Radio", "Tengrinews.kz, Zakon.kz, Informburo, Vlast.kz",
    "WhatsApp, YouTube, Instagram, Telegram, TikTok"],
"KWT": ["Western Asia", "Kuwaiti Dinar (KWD)", ["Arabic (official)"], "Constitutional monarchy",
    ["Oil and gas", "Financial services", "Construction", "Shipping"],
    "A wealthy Gulf state with one of the world's highest per-capita incomes, built on oil reserves.",
    "KTV, Al Rai, Scope TV", "Radio Kuwait, Marina FM, Pulse 88.8", "Kuwait Times, Arab Times, Al Qabas, Al Anbaa",
    "WhatsApp, Instagram, YouTube, Snapchat, TikTok, X"],
"KGZ": ["Central Asia", "Kyrgyzstani Som (KGS)", ["Kyrgyz (official)", "Russian (official)"], "Presidential republic",
    ["Mining", "Agriculture", "Hydropower", "Remittances"],
    "A mountainous Central Asian republic known for its nomadic heritage and growing gold mining sector.",
    "KTRK, NTS, 5 Kanal", "Birinchi Radio, Azattyk, Radio Maral", "Kloop, 24.kg, Akipress, Sputnik Kyrgyzstan",
    "WhatsApp, Facebook, YouTube, Instagram, Telegram"],
"LAO": ["South-Eastern Asia", "Lao Kip (LAK)", ["Lao (official)"], "One-party socialist republic",
    ["Hydroelectric power", "Mining", "Agriculture", "Tourism"],
    "A landlocked Southeast Asian country with significant hydroelectric potential, often called the 'Battery of Southeast Asia.'",
    "Lao National TV, Lao Star", "Lao National Radio, FM 103.7", "Vientiane Times, Lao News Agency (KPL)",
    "Facebook, WhatsApp, YouTube, TikTok"],
"LBN": ["Western Asia", "Lebanese Pound (LBP)", ["Arabic (official)", "French (widely spoken)", "English"], "Parliamentary republic",
    ["Services", "Banking", "Tourism", "Diaspora remittances"],
    "A Middle Eastern country with a historically vibrant and pluralistic media scene, now navigating severe economic crisis.",
    "LBCI, MTV Lebanon, OTV, Al Jadeed, Tele Liban", "NRJ Lebanon, Radio Liban, Voice of Lebanon, Nostalgie", "L'Orient Today, Naharnet, The961, Annahar, Megaphone",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"MDV": ["Southern Asia", "Maldivian Rufiyaa (MVR)", ["Dhivehi (official)"], "Presidential republic",
    ["Tourism", "Fishing", "Shipping"],
    "An Indian Ocean archipelago of over 1,000 islands, with an economy almost entirely driven by luxury tourism.",
    "PSM, Raajje TV, Sangu TV, Channel 13", "Dhivehi FM, Voice of Maldives", "Mihaaru, Sun Online, The Edition, Avas",
    "Facebook, WhatsApp, YouTube, Instagram, Telegram, TikTok"],
"MNG": ["Eastern Asia", "Mongolian Tugrik (MNT)", ["Mongolian (official)"], "Parliamentary republic",
    ["Mining", "Agriculture", "Livestock", "Tourism"],
    "A vast, sparsely populated landlocked country between China and Russia, with a rapidly growing mining sector.",
    "MNB, TV5, TV9, NTV", "MNB Radio, Mongol FM, 107.5", "UB Post, News.mn, MONTSAME, Ikon.mn",
    "Facebook, YouTube, Instagram, TikTok"],
"OMN": ["Western Asia", "Omani Rial (OMR)", ["Arabic (official)"], "Absolute monarchy",
    ["Oil and gas", "Tourism", "Logistics", "Fishing", "Manufacturing"],
    "A Gulf state on the Arabian Peninsula's southeastern coast, diversifying its economy away from oil dependence.",
    "Oman TV, Al Jazeera Sport", "Radio Sultanate of Oman, Hi FM, Merge FM", "Times of Oman, Muscat Daily, Oman Observer",
    "WhatsApp, Instagram, YouTube, TikTok, Snapchat"],
"PRK": ["Eastern Asia", "North Korean Won (KPW)", ["Korean (official)"], "One-party totalitarian state",
    ["Heavy industry", "Mining", "Agriculture", "Military"],
    "One of the world's most isolated countries, with fully state-controlled media and severely restricted internet access.",
    "Korean Central Television (KCTV), Mansudae TV", "Korean Central Broadcasting Station, Pyongyang FM", "KCNA (Korean Central News Agency), Rodong Sinmun",
    "None (internet access severely restricted)"],
"QAT": ["Western Asia", "Qatari Riyal (QAR)", ["Arabic (official)"], "Absolute monarchy",
    ["Natural gas", "Oil", "Finance", "Sports infrastructure"],
    "A wealthy Gulf peninsula state, home to Al Jazeera and one of the world's highest per-capita incomes.",
    "Al Jazeera, QTV, Al Kass, beIN Sports", "QBS Radio, Al Jazeera Radio", "The Peninsula, Gulf Times, Al Jazeera.net, Doha News",
    "WhatsApp, Instagram, YouTube, Snapchat, TikTok, X"],
"SGP": ["South-Eastern Asia", "Singapore Dollar (SGD)", ["English (official)", "Mandarin (official)", "Malay (official)", "Tamil (official)"], "Parliamentary republic",
    ["Financial services", "Electronics", "Biotechnology", "Oil refining", "Shipping"],
    "A prosperous city-state and global financial center with one of Asia's most developed media landscapes.",
    "Channel NewsAsia (CNA), Channel 5, Channel 8, Channel U", "938Live, Capital 958, Gold 905, Kiss92", "The Straits Times, CNA, TODAY, Mothership, The Online Citizen",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"LKA": ["Southern Asia", "Sri Lankan Rupee (LKR)", ["Sinhala (official)", "Tamil (official)"], "Presidential republic",
    ["Garments", "Tea", "Tourism", "Rubber", "IT services"],
    "An Indian Ocean island nation south of India, with a diverse media landscape and a growing ICT sector.",
    "Rupavahini, Sirasa TV, Hiru TV, Derana TV", "SLBC, Sirasa FM, Hiru FM, Shakthi FM", "Daily Mirror, Daily News, NewsFirst, Colombo Gazette, Groundviews",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"SYR": ["Western Asia", "Syrian Pound (SYP)", ["Arabic (official)"], "Transitional government",
    ["Agriculture", "Oil", "Manufacturing", "Mining"],
    "A Middle Eastern country at the crossroads of civilizations, rebuilding after over a decade of civil conflict.",
    "Syrian TV, Sama TV, Orient TV", "Syrian Arab Radio, Sham FM", "SANA, Syrian Observer, Enab Baladi, Syria Direct",
    "WhatsApp, Facebook, YouTube, Telegram"],
"TJK": ["Central Asia", "Tajikistani Somoni (TJS)", ["Tajik (official)", "Russian (widely spoken)"], "Presidential republic",
    ["Aluminum", "Cotton", "Hydropower", "Agriculture", "Remittances"],
    "Central Asia's smallest and most mountainous country, with an economy heavily dependent on remittances from Russia.",
    "TVT, Safina TV, Jahonnamo", "Radio Tajikistan, Asia Plus, Radio Imruz", "Asia-Plus, Avesta, Akhbor",
    "Facebook, YouTube, Instagram, Telegram, TikTok"],
"TKM": ["Central Asia", "Turkmenistani Manat (TMT)", ["Turkmen (official)"], "Presidential republic",
    ["Natural gas", "Oil", "Cotton", "Agriculture"],
    "A Central Asian country with the world's fourth-largest natural gas reserves and a highly restricted media environment.",
    "Altyn Asyr, Yaslyk, Türkmenistan TV", "Turkmen Radio, Watan, Çar Tarapdan", "TDH (Turkmenistan State News), Turkmenportal",
    "WhatsApp, Instagram, YouTube, IMO"],
"ARE": ["Western Asia", "UAE Dirham (AED)", ["Arabic (official)", "English (widely spoken)"], "Federal monarchy",
    ["Oil and gas", "Real estate", "Tourism", "Finance", "Aviation", "Technology"],
    "A wealthy Gulf federation of seven emirates, with Dubai and Abu Dhabi serving as global business, tourism, and media hubs.",
    "Abu Dhabi TV, Dubai TV, Al Arabiya, MBC, Sky News Arabia", "Abu Dhabi FM, Dubai Eye 103.8, Virgin Radio Dubai, ARN Network", "Gulf News, Khaleej Times, The National, Arabian Business",
    "WhatsApp, Instagram, YouTube, TikTok, Snapchat, X"],
"UZB": ["Central Asia", "Uzbekistani Som (UZS)", ["Uzbek (official)", "Russian"], "Presidential republic",
    ["Natural gas", "Cotton", "Gold mining", "Agriculture", "Textiles"],
    "Central Asia's most populous country, undergoing significant economic liberalization and opening to foreign investment.",
    "Uzbekistan TV, Yoshlar, Zo'r TV, MY5", "Uzbek Radio, Oriat FM, Navruz FM", "Gazeta.uz, Kun.uz, Podrobno.uz, Spot.uz",
    "Telegram, YouTube, Instagram, Facebook, TikTok"],
"TLS": ["South-Eastern Asia", "United States Dollar (USD)", ["Portuguese (official)", "Tetum (official)"], "Semi-presidential republic",
    ["Oil and gas", "Agriculture", "Coffee", "Tourism"],
    "Southeast Asia's youngest nation (independent 2002), relying on petroleum revenues while building its agricultural and tourism sectors.",
    "TVTL, GMN TV", "Radio Timor-Leste, Radio Rakambia, Radio Komunidade", "Tatoli ba Kultura, Tempo Timor, Timor Post",
    "Facebook, WhatsApp, YouTube"],
"PSE": ["Western Asia", "Israeli New Shekel (ILS) / Jordanian Dinar (JOD)", ["Arabic (official)"], "Semi-presidential system",
    ["Agriculture", "Services", "Construction", "Telecommunications"],
    "A UN observer state comprising the West Bank and Gaza Strip, with a young, highly connected population and a resilient media sector.",
    "Palestine TV, Al-Aqsa TV, Watan TV, Maan TV", "Voice of Palestine, Ajyal Radio, Raya FM", "Wafa, Ma'an News, Quds News Network, Filastin",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],

# ---- EUROPE ----
"ALB": ["Southern Europe", "Albanian Lek (ALL)", ["Albanian (official)"], "Parliamentary republic",
    ["Mining", "Agriculture", "Tourism", "Textiles", "Energy"],
    "A Southeastern European country on the Adriatic coast with a growing tourism sector and a liberalized media landscape.",
    "RTSH, Top Channel, TV Klan, Vizion Plus", "Radio Tirana, Top Albania Radio, Radio Klan", "Shqiptarja.com, BalkanWeb, Exit.al, Reporter.al",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"AND": ["Southern Europe", "Euro (EUR)", ["Catalan (official)", "Spanish", "French"], "Parliamentary co-principality",
    ["Tourism", "Financial services", "Retail", "Skiing"],
    "A micro-state in the Pyrenees between France and Spain, known for ski tourism and duty-free shopping.",
    "ATV (Andorra Televisió)", "RNA (Radio Nacional d'Andorra)", "Diari d'Andorra, ANA, Bondia",
    "WhatsApp, Facebook, YouTube, Instagram"],
"AUT": ["Western Europe", "Euro (EUR)", ["German (official)"], "Federal parliamentary republic",
    ["Manufacturing", "Tourism", "Technology", "Financial services", "Agriculture"],
    "A prosperous Central European country known for its cultural heritage, alpine tourism, and strong manufacturing sector.",
    "ORF, Puls 4, ServusTV, ATV", "Ö1, Ö3, FM4, Kronehit", "ORF.at, Der Standard, Die Presse, Kurier",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"BLR": ["Eastern Europe", "Belarusian Ruble (BYN)", ["Belarusian (official)", "Russian (official)"], "Presidential republic",
    ["Manufacturing", "Machinery", "Agriculture", "IT", "Petrochemicals"],
    "An Eastern European country with a state-dominated media environment and a growing IT sector.",
    "Belarus 1, ONT, STV, CTV", "Radio Belarus, Radius FM, Unistar", "Tut.by (blocked), Nasha Niva, Zerkalo.io, Belsat",
    "WhatsApp, Telegram, YouTube, Instagram, VK"],
"BEL": ["Western Europe", "Euro (EUR)", ["Dutch (official)", "French (official)", "German (official)"], "Federal parliamentary monarchy",
    ["Manufacturing", "Chemicals", "Financial services", "Logistics", "Pharmaceuticals"],
    "Home to EU and NATO headquarters, a trilingual federal state with separate Dutch- and French-language media systems.",
    "VRT (Dutch), RTBF (French), BRF (German)", "Radio 1, La Première, BRF, Nostalgie", "VRT NWS, RTBF Info, De Standaard, Le Soir, HLN",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"BIH": ["Southern Europe", "Bosnia and Herzegovina Convertible Mark (BAM)", ["Bosnian", "Croatian", "Serbian"], "Parliamentary republic",
    ["Manufacturing", "Mining", "Agriculture", "Energy", "Tourism"],
    "A Southeastern European country with a complex post-conflict political structure and ethnically divided media landscape.",
    "BHT1, FTV, RTRS, Hayat TV", "BH Radio 1, Radio FBiH, Radio RS, Hayat Radio", "Klix.ba, N1 BiH, Oslobođenje, Dnevni Avaz",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"BGR": ["Eastern Europe", "Bulgarian Lev (BGN)", ["Bulgarian (official)"], "Parliamentary republic",
    ["Manufacturing", "Tourism", "ICT", "Agriculture", "Energy"],
    "An EU member state in Southeastern Europe with a growing IT outsourcing sector and Black Sea tourism.",
    "BNT, bTV, Nova TV, Bulgaria On Air", "BNR, Darik Radio, bTV Radio, Radio FM+", "Dnevnik.bg, Mediapool, Capital.bg, 24chasa.bg",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"HRV": ["Southern Europe", "Euro (EUR)", ["Croatian (official)"], "Parliamentary republic",
    ["Tourism", "Shipbuilding", "Food processing", "Pharmaceuticals", "ICT"],
    "An EU and Eurozone member on the Adriatic coast, with tourism as a major economic driver.",
    "HRT, Nova TV, RTL Croatia, N1", "HRT Radio, Otvoreni Radio, Narodni Radio, Antena Zagreb", "Index.hr, Jutarnji.hr, Net.hr, Večernji.hr",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"CYP": ["Southern Europe", "Euro (EUR)", ["Greek (official)", "Turkish (official)"], "Presidential republic",
    ["Tourism", "Financial services", "Shipping", "Real estate"],
    "A Mediterranean island at the crossroads of Europe, Asia, and Africa, with a divided territory and a services-based economy.",
    "RIK, Sigma TV, ANT1 Cyprus, Omega", "RIK Radio, Super FM, Proto Radio", "Philenews, In-Cyprus, Sigmalive, Cyprus Mail",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"CZE": ["Central Europe", "Czech Koruna (CZK)", ["Czech (official)"], "Parliamentary republic",
    ["Manufacturing", "Automotive", "IT", "Tourism", "Engineering"],
    "A Central European industrial powerhouse known for automotive manufacturing and a vibrant cultural heritage.",
    "ČT, Nova, Prima, Barrandov TV", "Český rozhlas, Frekvence 1, Evropa 2, Impuls", "iDNES.cz, Novinky.cz, Seznam Zprávy, Aktuálně.cz",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"DNK": ["Northern Europe", "Danish Krone (DKK)", ["Danish (official)"], "Constitutional monarchy",
    ["Pharmaceuticals", "Shipping", "Wind energy", "Agriculture", "Technology"],
    "A Scandinavian country known for high living standards, wind energy leadership, and a strong public media tradition.",
    "DR, TV 2 Denmark", "DR Radio (P1-P4), Radio24syv, Nova FM", "DR.dk, BT, Politiken, Berlingske, Jyllands-Posten",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"EST": ["Northern Europe", "Euro (EUR)", ["Estonian (official)"], "Parliamentary republic",
    ["ICT", "Electronics", "Timber", "Telecommunications", "Fintech"],
    "A digitally advanced Baltic state and EU member, widely recognized as a pioneer in e-government and digital society.",
    "ERR (ETV, ETV2), Kanal 2, TV3 Estonia", "ERR Radio, Sky Plus, Star FM", "Delfi, Postimees, ERR News, Eesti Päevaleht",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"FIN": ["Northern Europe", "Euro (EUR)", ["Finnish (official)", "Swedish (official)"], "Parliamentary republic",
    ["Technology", "Forestry", "Engineering", "Telecommunications", "Design"],
    "A Nordic country known for its education system, technology sector, and one of the world's highest press freedom rankings.",
    "Yle (TV1, TV2), MTV3, Nelonen", "Yle Radio (Suomi, Puhe, Vega), Radio Nova, NRJ", "Yle.fi, Helsingin Sanomat, Ilta-Sanomat, Iltalehti",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"GRC": ["Southern Europe", "Euro (EUR)", ["Greek (official)"], "Parliamentary republic",
    ["Tourism", "Shipping", "Agriculture", "Food processing", "Energy"],
    "A Southern European country with an outsized role in global shipping and a tourism-driven economy centered on its islands and archaeological heritage.",
    "ERT, Mega, ANT1, SKAI, Star Channel", "ERA, SKAI Radio, Real FM, Athens 9.84", "Kathimerini, Protothema, Naftemporiki, in.gr, CNN Greece",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"HUN": ["Central Europe", "Hungarian Forint (HUF)", ["Hungarian (official)"], "Parliamentary republic",
    ["Automotive", "Electronics", "Pharmaceuticals", "Agriculture", "Tourism"],
    "A Central European country with a significant automotive industry, whose media landscape has seen increasing government influence.",
    "MTVA (M1-M5), RTL Klub, TV2 Hungary, ATV", "Kossuth Rádió, Petőfi Rádió, Retro Rádió, Klub Rádió", "Index.hu, HVG, 444.hu, Telex, G7",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"ISL": ["Northern Europe", "Icelandic Króna (ISK)", ["Icelandic (official)"], "Parliamentary republic",
    ["Fishing", "Aluminum smelting", "Tourism", "Geothermal energy"],
    "A small, highly connected North Atlantic island nation with a vibrant media scene relative to its population size.",
    "RÚV (Sjónvarpið)", "RÚV (Rás 1, Rás 2), Bylgjan, FM957, Útvarp Saga", "Vísir, mbl.is, RÚV, Stundin",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Snapchat"],
"IRL": ["Northern Europe", "Euro (EUR)", ["English", "Irish (official)"], "Parliamentary republic",
    ["Technology", "Pharmaceuticals", "Financial services", "Agriculture", "Tourism"],
    "An EU member that hosts European headquarters for many major tech firms, with a vibrant English-language media market.",
    "RTÉ, Virgin Media Television, TG4", "RTÉ Radio (Radio 1, 2FM, lyric fm), Newstalk, Today FM", "RTÉ News, The Journal, Irish Times, Irish Independent, TheJournal.ie",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, X"],
"LVA": ["Northern Europe", "Euro (EUR)", ["Latvian (official)"], "Parliamentary republic",
    ["Manufacturing", "ICT", "Timber", "Food processing", "Logistics"],
    "A Baltic EU and NATO member with a significant Russian-speaking minority and a media landscape reflecting both communities.",
    "LTV (LTV1, LTV7), TV3 Latvia", "Latvijas Radio (LR1-LR4), Star FM, EHR", "Delfi.lv, LSM, TVNET, la.lv",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"LIE": ["Western Europe", "Swiss Franc (CHF)", ["German (official)"], "Constitutional monarchy",
    ["Financial services", "Manufacturing", "Dental products", "Ceramics"],
    "One of Europe's smallest countries, a prosperous Alpine principality between Austria and Switzerland.",
    "1FLTV (Liechtenstein Television)", "Radio Liechtenstein", "Vaterland, Volksblatt",
    "WhatsApp, Facebook, YouTube, Instagram"],
"LTU": ["Northern Europe", "Euro (EUR)", ["Lithuanian (official)"], "Parliamentary republic",
    ["Manufacturing", "Laser technology", "ICT", "Agriculture", "Furniture"],
    "The largest Baltic state by population, an EU member with a strong manufacturing base and growing tech sector.",
    "LRT, TV3, LNK, BTV", "LRT Radijas, M-1 Plius, Žinių Radijas, Power Hit Radio", "Delfi.lt, 15min.lt, LRT.lt, VZ.lt",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"LUX": ["Western Europe", "Euro (EUR)", ["Luxembourgish (official)", "French (official)", "German (official)"], "Constitutional monarchy",
    ["Financial services", "Steel", "Telecommunications", "Satellite operations"],
    "A small, wealthy country and EU founding member, home to major European institutions and a global financial center.",
    "RTL Lëtzebuerg", "RTL Radio, Radio 100.7, Eldoradio", "RTL.lu, Tageblatt, Paperjam, Luxemburger Wort",
    "WhatsApp, Facebook, YouTube, Instagram"],
"MLT": ["Southern Europe", "Euro (EUR)", ["Maltese (official)", "English (official)"], "Parliamentary republic",
    ["Tourism", "iGaming", "Financial services", "Film production", "Maritime"],
    "A small Mediterranean island state with a thriving iGaming and financial services sector.",
    "TVM, ONE TV, NET TV, Xejk TV", "PBS Radio, Bay Radio, Xfm, Magic", "Times of Malta, MaltaToday, Lovin Malta, The Shift",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"MDA": ["Eastern Europe", "Moldovan Leu (MDL)", ["Romanian (official)", "Russian"], "Parliamentary republic",
    ["Agriculture", "Wine production", "Textiles", "Remittances"],
    "A small Eastern European country between Romania and Ukraine, known for its wine industry and aspirations for EU integration.",
    "Moldova 1, Jurnal TV, TV8, NTV Moldova", "Radio Moldova, Jurnal FM, Radio Plai", "Newsmaker.md, Jurnal.md, Ziarul de Gardă, Diez.md",
    "WhatsApp, Facebook, YouTube, Instagram, Telegram, TikTok"],
"MCO": ["Western Europe", "Euro (EUR)", ["French (official)"], "Constitutional monarchy",
    ["Tourism", "Finance", "Real estate", "Gambling"],
    "The world's second-smallest country by area, a wealthy Mediterranean city-state known for its casino and luxury tourism.",
    "TMC (Télé Monte-Carlo), Monaco Info", "Radio Monte-Carlo, Riviera Radio, Radio Monaco", "Monaco Tribune, Monaco Matin",
    "WhatsApp, Facebook, YouTube, Instagram"],
"MNE": ["Southern Europe", "Euro (EUR)", ["Montenegrin (official)"], "Parliamentary republic",
    ["Tourism", "Aluminum", "Agriculture", "Energy"],
    "A small Adriatic country with a growing coastal tourism sector and EU candidate status.",
    "RTCG (TVCG1, TVCG2), Vijesti TV", "Radio Crne Gore, Antena M, Radio Jadran", "Vijesti.me, CdM, Analitika, Pobjeda",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"NLD": ["Western Europe", "Euro (EUR)", ["Dutch (official)", "Frisian"], "Constitutional monarchy",
    ["Trade", "Agriculture", "Technology", "Financial services", "Energy"],
    "A major European trading nation and EU founding member, known for its liberal media landscape and global port at Rotterdam.",
    "NPO (NPO 1/2/3), RTL, SBS", "NPO Radio 1, Radio 538, 3FM, BNR", "NOS, NU.nl, De Telegraaf, Volkskrant, AD, RTVNieuws",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"MKD": ["Southern Europe", "Macedonian Denar (MKD)", ["Macedonian (official)", "Albanian (official)"], "Parliamentary republic",
    ["Manufacturing", "Agriculture", "Mining", "Services", "Textiles"],
    "A landlocked Southeastern European country with a mixed media landscape and EU candidate status.",
    "MRT, Sitel, Telma, Alsat M", "Macedonian Radio, Kanal 77, Antenna 5", "MKD.mk, A1on, SDK, Prizma",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"NOR": ["Northern Europe", "Norwegian Krone (NOK)", ["Norwegian (official)", "Sami"], "Constitutional monarchy",
    ["Oil and gas", "Shipping", "Fishing", "Hydropower", "Technology"],
    "A wealthy Scandinavian country with a sovereign wealth fund built on oil revenues and a strong public broadcasting tradition.",
    "NRK, TV 2 Norway, TVNorge", "NRK Radio (P1-P3), P4, Radio Norge", "NRK.no, VG, Dagbladet, Aftenposten, Nettavisen",
    "WhatsApp, Facebook, YouTube, Instagram, Snapchat, TikTok"],
"PRT": ["Southern Europe", "Euro (EUR)", ["Portuguese (official)"], "Semi-presidential republic",
    ["Tourism", "Manufacturing", "Cork", "Wine", "Technology"],
    "A Southern European country with a growing tech scene and strong cultural ties to Portuguese-speaking countries worldwide.",
    "RTP, SIC, TVI, CNN Portugal", "Antena 1, RFM, Renascença, TSF", "Público, Observador, Jornal de Notícias, Expresso, SAPO",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"ROU": ["Eastern Europe", "Romanian Leu (RON)", ["Romanian (official)"], "Semi-presidential republic",
    ["Automotive", "IT", "Agriculture", "Energy", "Tourism"],
    "An EU member with one of Europe's fastest-growing IT sectors and a dynamic, competitive media landscape.",
    "TVR, Pro TV, Antena 3, Digi24, Realitatea", "Radio România, Europa FM, Kiss FM, Digi FM", "HotNews, G4Media, Digi24.ro, Libertatea",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"SMR": ["Southern Europe", "Euro (EUR)", ["Italian (official)"], "Parliamentary republic",
    ["Tourism", "Banking", "Manufacturing", "Ceramics"],
    "The world's oldest republic and one of Europe's smallest states, an enclave within Italy.",
    "San Marino RTV", "Radio San Marino", "San Marino RTV Online, La Tribuna Sammarinese",
    "WhatsApp, Facebook, YouTube, Instagram"],
"SRB": ["Southern Europe", "Serbian Dinar (RSD)", ["Serbian (official)"], "Parliamentary republic",
    ["Manufacturing", "Agriculture", "Mining", "ICT", "Automotive"],
    "A Western Balkan country with a competitive media market and EU candidate status.",
    "RTS, Pink, B92, Prva, N1 Serbia", "B92 Radio, Radio Belgrade, S Radio", "Blic, B92.net, N1, Danas, Nova.rs",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Telegram"],
"SVK": ["Central Europe", "Euro (EUR)", ["Slovak (official)"], "Parliamentary republic",
    ["Automotive", "Electronics", "IT", "Agriculture", "Energy"],
    "A Central European country with the world's highest per-capita car production and a growing services sector.",
    "RTVS (Jednotka, Dvojka), Markíza, JOJ, TA3", "Rádio Slovensko, Fun Radio, Rádio Expres", "SME.sk, Aktuality.sk, Denník N, Pravda.sk",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"SVN": ["Southern Europe", "Euro (EUR)", ["Slovene (official)"], "Parliamentary republic",
    ["Manufacturing", "Tourism", "Automotive", "Pharmaceuticals", "Logistics"],
    "A small Alpine EU member bridging Central and Southeastern Europe, with a highly educated population and diversified economy.",
    "RTV Slovenija (TV SLO1, TV SLO2), POP TV, Kanal A, Planet TV", "Radio Slovenija, Radio 1, Val 202, Radio Center", "24ur.com, Delo, Dnevnik, Siol.net, N1 Slovenia",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"ESP": ["Southern Europe", "Euro (EUR)", ["Spanish (official)", "Catalan", "Basque", "Galician"], "Constitutional monarchy",
    ["Tourism", "Automotive", "Agriculture", "Renewable energy", "Financial services"],
    "One of Europe's largest economies and a major global tourism destination, with a robust and diverse media market in multiple languages.",
    "RTVE (TVE, La 2), Antena 3, Telecinco, La Sexta, Cuatro", "Cadena SER, COPE, RNE, Onda Cero, Los 40", "El País, El Mundo, elDiario.es, La Vanguardia, 20minutos",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, X"],
"SWE": ["Northern Europe", "Swedish Krona (SEK)", ["Swedish (official)"], "Constitutional monarchy",
    ["Manufacturing", "Technology", "Forestry", "Automotive", "Pharmaceuticals"],
    "A Scandinavian country known for innovation, a strong welfare state, and globally influential tech and music industries.",
    "SVT, TV4, TV3 Sweden", "SR (Sveriges Radio P1-P4), Mix Megapol, Rix FM, NRJ", "SVT Nyheter, DN.se, Aftonbladet, Expressen, GP.se",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok, Snapchat"],
"CHE": ["Western Europe", "Swiss Franc (CHF)", ["German (official)", "French (official)", "Italian (official)", "Romansh (official)"], "Federal republic",
    ["Financial services", "Pharmaceuticals", "Manufacturing", "Watchmaking", "Tourism"],
    "A neutral, multilingual Alpine country known for its financial sector, pharmaceutical industry, and direct democracy system.",
    "SRG SSR (SRF, RTS, RSI), 3+", "SRF, RTS, RSI, Energy, Radio 24", "20 Minuten, NZZ, Tages-Anzeiger, Le Temps, Blick",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"VAT": ["Southern Europe", "Euro (EUR)", ["Italian", "Latin (official)"], "Ecclesiastical elective monarchy",
    ["Religious governance", "Tourism", "Publishing"],
    "The world's smallest independent state and the spiritual center of the Roman Catholic Church, with a global media operation.",
    "Vatican Media (CTV)", "Vatican Radio", "Vatican News, L'Osservatore Romano",
    "YouTube, Facebook, Instagram, X"],

# ---- OCEANIA ----
"FJI": ["Melanesia", "Fijian Dollar (FJD)", ["English (official)", "Fijian (official)", "Hindi"], "Parliamentary republic",
    ["Tourism", "Sugar", "Fishing", "Garments", "Gold mining"],
    "A Pacific island nation and regional hub, known for tourism and serving as the headquarters of several Pacific organizations.",
    "Fiji TV (Fiji One), FBC TV, Mai TV", "Fiji Broadcasting (Radio Fiji 1/2), Communications Fiji (FM96, Legend FM)", "Fiji Times, Fiji Village, FBC News, Fiji Sun",
    "Facebook, WhatsApp, YouTube, Instagram, TikTok"],
"KIR": ["Micronesia", "Australian Dollar (AUD)", ["English (official)", "Gilbertese"], "Presidential republic",
    ["Fishing", "Copra", "Handicrafts"],
    "A scattered Pacific atoll nation across the equator, among the countries most vulnerable to climate change.",
    "N/A (no national TV service)", "Radio Kiribati", "Kiribati Updates, Pacific Islands News Association",
    "Facebook, WhatsApp"],
"MHL": ["Micronesia", "United States Dollar (USD)", ["Marshallese (official)", "English (official)"], "Presidential republic",
    ["Fishing", "Copra", "US military base hosting", "Shipping registration"],
    "A Pacific atoll nation with a Compact of Free Association with the United States.",
    "MBC TV", "V7AB Radio Marshalls", "Marshall Islands Journal",
    "Facebook, WhatsApp, YouTube"],
"FSM": ["Micronesia", "United States Dollar (USD)", ["English (official)"], "Federal presidential republic",
    ["Fishing", "Agriculture", "Tourism"],
    "A Pacific island federation of four states with a Compact of Free Association with the United States.",
    "N/A (no national TV service)", "V6AH Radio, FSM Radio", "The Kaselehlie Press",
    "Facebook, WhatsApp"],
"NRU": ["Micronesia", "Australian Dollar (AUD)", ["Nauruan (official)", "English"], "Parliamentary republic",
    ["Government services", "Phosphate mining", "Fishing"],
    "One of the world's smallest republics, a Pacific island historically reliant on phosphate mining.",
    "Nauru TV (NTV)", "Radio Nauru", "Nauru Government Information Office",
    "Facebook, WhatsApp"],
"NZL": ["Australasia", "New Zealand Dollar (NZD)", ["English", "Māori (official)", "NZ Sign Language"], "Constitutional monarchy",
    ["Agriculture", "Tourism", "Film production", "Technology", "Dairy"],
    "A Pacific nation known for strong democratic institutions, high quality of life, and a globally competitive agricultural sector.",
    "TVNZ, Three (Newshub), Māori Television", "RNZ, Newstalk ZB, The Hits, More FM", "Stuff.co.nz, NZ Herald, RNZ.co.nz, Newsroom, The Spinoff",
    "WhatsApp, Facebook, YouTube, Instagram, TikTok"],
"PLW": ["Micronesia", "United States Dollar (USD)", ["Palauan (official)", "English (official)"], "Presidential republic",
    ["Tourism", "Fishing", "Subsistence agriculture"],
    "A small Pacific archipelago known for its pristine marine environments and diving tourism.",
    "Palau National TV", "WWFM, T8AA Radio", "Island Times, Tia Belau",
    "Facebook, WhatsApp, YouTube"],
"PNG": ["Melanesia", "Papua New Guinean Kina (PGK)", ["English (official)", "Tok Pisin (official)", "Hiri Motu (official)"], "Constitutional monarchy",
    ["Mining", "Oil and gas", "Agriculture", "Forestry", "Fishing"],
    "The Pacific's most linguistically diverse country with over 800 languages, rich in natural resources.",
    "EMTV, NBC TV", "NBC Radio, FM100, Nau FM, Yumi FM", "Post-Courier, The National, Loop PNG",
    "Facebook, WhatsApp, YouTube"],
"WSM": ["Polynesia", "Samoan Tala (WST)", ["Samoan (official)", "English (official)"], "Parliamentary republic",
    ["Agriculture", "Fishing", "Tourism", "Remittances"],
    "A Polynesian island nation and the first Pacific country to gain independence, with strong cultural traditions.",
    "TV3 Samoa, Samoa Broadcasting Corporation TV", "Radio 2AP, Magik FM, Talofa FM", "Samoa Observer, Talamua, Samoa Global News",
    "Facebook, WhatsApp, YouTube"],
"SLB": ["Melanesia", "Solomon Islands Dollar (SBD)", ["English (official)"], "Constitutional monarchy",
    ["Forestry", "Fishing", "Agriculture", "Mining"],
    "A Melanesian archipelago nation with significant natural resources and a growing logging-based economy.",
    "SIBC TV", "SIBC Radio, Paoa FM, ZFM", "Solomon Star, Island Sun, Solomon Times",
    "Facebook, WhatsApp, YouTube"],
"TON": ["Polynesia", "Tongan Paʻanga (TOP)", ["Tongan (official)", "English (official)"], "Constitutional monarchy",
    ["Agriculture", "Fishing", "Tourism", "Remittances"],
    "The Pacific's last remaining monarchy, a Polynesian kingdom with a strong cultural identity.",
    "Tonga Broadcasting Commission TV", "Radio Tonga, FM 87.5, Radio Nuku'alofa", "Matangi Tonga, Kaniva Tonga",
    "Facebook, WhatsApp, YouTube"],
"TUV": ["Polynesia", "Australian Dollar (AUD)", ["Tuvaluan (official)", "English (official)"], "Constitutional monarchy",
    ["Fishing", "Government services", ".tv domain licensing"],
    "The world's fourth-smallest country by area and among the most climate-vulnerable, supplementing its economy through its .tv internet domain.",
    "N/A (no national TV service)", "Radio Tuvalu", "Tuvalu-News",
    "Facebook, WhatsApp"],
"VUT": ["Melanesia", "Vanuatu Vatu (VUV)", ["Bislama (official)", "English (official)", "French (official)"], "Parliamentary republic",
    ["Agriculture", "Tourism", "Fishing", "Offshore finance"],
    "A Melanesian archipelago nation with a diverse economy based on agriculture, tourism, and offshore finance.",
    "VBTC TV", "Radio Vanuatu, FM 107, Buzz FM", "Daily Post Vanuatu, Vanuatu Daily, Vanuatu News",
    "Facebook, WhatsApp, YouTube"],
}

def build():
    # Load existing curated data
    existing = json.loads(STATIC.read_text(encoding="utf-8"))
    comment = existing.pop("_comment", "")

    # Load World Bank data
    wb_path = Path("/tmp/wb_countries.json")
    wb_lookup = {}
    if wb_path.exists():
        with open(wb_path) as f:
            raw = json.load(f)
        for c in raw[1]:
            if c.get("region", {}).get("value") != "Aggregates":
                wb_lookup[c["id"]] = c
    else:
        print("Warning: /tmp/wb_countries.json not found. Using compiled data only.")

    result = {"_comment": comment}

    # Preserve all existing entries (higher quality, hand-curated)
    for iso3, entry in existing.items():
        if iso3.startswith("_"):
            continue
        result[iso3] = entry

    # Add new countries
    added = 0
    for iso3, vals in sorted(D.items()):
        if iso3 in result:
            continue

        subregion, currency, languages, government, industries = vals[0], vals[1], vals[2], vals[3], vals[4]
        overview, tv, radio, online, social = vals[5], vals[6], vals[7], vals[8], vals[9]

        # Get name and capital from World Bank, fall back to defaults.
        # A few UN-recognised states are absent from the World Bank API —
        # without this map their ISO code would leak through as their name.
        WB_MISSING = {
            "VAT": ("Holy See", "Vatican City", "VA"),
            "PRK": ("Korea, Dem. People's Rep.", "Pyongyang", "KP"),
        }
        wb = wb_lookup.get(iso3, {})
        fallback_name, fallback_capital, fallback_iso2 = WB_MISSING.get(iso3, (iso3, "", iso3[:2]))
        name = wb.get("name") or fallback_name
        capital = wb.get("capitalCity") or fallback_capital
        iso2 = wb.get("iso2Code") or fallback_iso2

        # Map subregion → region (subregion is always correct, WB region is too broad)
        if subregion in ("Western Africa", "Eastern Africa", "Middle Africa", "Southern Africa", "Northern Africa"):
            region = "Africa"
        elif subregion in ("Caribbean", "Central America", "South America", "Northern America"):
            region = "Americas"
        elif subregion in ("Melanesia", "Micronesia", "Polynesia", "Australasia"):
            region = "Oceania"
        elif subregion in ("Northern Europe", "Western Europe", "Southern Europe", "Eastern Europe", "Central Europe"):
            region = "Europe"
        else:
            region = "Asia"

        entry = {
            "name": name,
            "capital": capital,
            "region": region,
            "subregion": subregion,
            "flag": flag_emoji(iso2),
            "overview": overview,
            "currency": currency,
            "languages": languages,
            "government": government,
            "dominant_industries": industries,
            "focus_areas": ["Economic development", "Digital infrastructure", "Regional cooperation", "Climate action"],
            "media": {
                "top_tv": tv,
                "top_radio": radio,
                "top_online_news": online,
                "top_social": social,
            },
            "topics_of_interest": ["Politics", "Economy", "Local news", "Sports", "Social issues"],
        }
        result[iso3] = entry
        added += 1

    # Write output
    STATIC.write_text(
        json.dumps(result, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    total = len([k for k in result if not k.startswith("_")])
    print(f"Done. Added {added} new countries. Total: {total} countries in static_countries.json")

if __name__ == "__main__":
    build()
